### ISSUE TITLE
修复滚动条位置与显示数值不同步问题

### ISSUE THREAD

**Issue by chenjunfu2** [LeaversFly/AIvoice#1]
将index.js中的
document.querySelectorAll(".slide").forEach((e=>{
        e.addEventListener("input", (e=>r[e.target.name] = e.target.value))
    }
    ))
代码段，替换为
document.querySelectorAll(".slide").forEach((e => {
    e.addEventListener("input", (e => {
        r[e.target.name] = e.target.value;
        e.target.parentNode.querySelector(".param.tag").innerHTML = e.target.value;}))
    }
    ))
或类似操作，在拖动时更新数值以同步

下面是有关此故障的视频
https://github.com/LeaversFly/AIvoice/assets/64954184/9b3a9ff9-14e5-4352-9278-0d2a1b80fdfd

**Comment by LeaversFly** [comment]
感谢反馈，已修复
